<script type="text/javascript">
require([
  'aos'
], function(aos) {
  'use strict';

  function addMarginForFooter() {
    let addToCartSticky = document.querySelector('[data-aos-id="addtocart-sticky"]');

    if (addToCartSticky) {
      let footer = document.querySelector('footer');
      footer.style.marginBottom = addToCartSticky.offsetHeight + 'px';
    }
  }

  aos.init();
  addMarginForFooter();

  window.addEventListener('resize', function () {
    addMarginForFooter();
  });

  window.addEventListener('onload', function () {
    addMarginForFooter();
  });
});
</script>
